app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("front.urls")),
    path("", include("back.urls")),
    path("unicorn/", include("django_unicorn.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/back/urls.py
from back.views.log_in_view import LogInView
from back.views.sign_up_view import SignUpView
from django.urls import path


urlpatterns = [
    path("sign-up/", SignUpView.as_view(), name="sign-up"),
    path('login/', LogInView.as_view(), name='login')
]

app/back/models/client_model.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from uuid import uuid4


class ClientModel(AbstractUser):
    uuid = models.UUIDField(primary_key=True, default=uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.username
    

app/back/forms/sign_up_form.py
from back.models.client_model import ClientModel
from django import forms


class SignUpForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.TextInput())
    last_name = forms.CharField(required=True, widget=forms.TextInput())
    username = forms.CharField(required=True, widget=forms.EmailInput())
    password = forms.CharField(required=True, widget=forms.PasswordInput())
    repeat_password = forms.CharField(required=True, widget=forms.PasswordInput())

    class Meta:
        model = ClientModel
        fields = ["first_name", "last_name", "username", "password", "repeat_password", ]
        

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        tailwind_common_class = "p-2 border-b border-b-1 border-primary-earth_tone_4 outline-primary-earth_tone_4"
        tailwind_extra_class = {
            "password": "w-full"
        }
        
        for field_name, field in self.fields.items():
            field.widget.attrs.update({"class": tailwind_common_class})

            if field_name in tailwind_extra_class:
                field.widget.attrs["class"] += f" {tailwind_extra_class[field_name]}"
                

app/back/views/log_in_view.py
import logging
from back.models.client_model import ClientModel
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.template import loader
from django.template.response import TemplateResponse

logger = logging.getLogger(__name__)


class LogInView(LoginView):

    def get(self, request: HttpRequest) -> HttpResponse:
        template = loader.get_template("registration/login.html")
        return HttpResponse(template.render(None, request))
    
    def form_valid(self, form: AuthenticationForm) -> TemplateResponse:
        messages.success(self.request, "Inicio de sesión exitoso")
        return super().form_valid(form)
        
    def form_invalid(self, form: AuthenticationForm) -> TemplateResponse:
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = ClientModel.objects.filter(username=username).exists()
        if user:
            user = ClientModel.objects.get(username=username)
            checked_password = check_password(password, user.password)
            if not checked_password:
                logger.info(f"Wrong password")
                messages.error(self.request, "La contraseña es incorrecta")
        else:
            logger.info(f"User doesn't exist")
            messages.error(self.request, "El usuario es incorrecto")
        return super().form_invalid(form)
    

app/back/views/sign_up_view.py
import logging
from back.forms.sign_up_form import SignUpForm
from back.handlers.sign_up_exception_handler import SignUpExceptionHandler
from back.models.client_model import ClientModel
from back.services.client_service import ClientService
from back.services.sign_up_service import SignUpService
from django.contrib import messages
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.template import loader
from django.views import View

logger = logging.getLogger(__name__)


class SignUpView(View):

    def get(self, request: HttpRequest) -> HttpResponse:
        template = loader.get_template("sign-up.html")
        context = {
            "form": SignUpForm
        }
        return HttpResponse(template.render(context, request))
    
    def post(self, request: HttpRequest) -> HttpResponseRedirect:
        form = SignUpForm(request.POST)
        sign_up_service = SignUpService(form)
        client_service = ClientService()

        try:
            validated_form: dict = sign_up_service.validate_form()
            user: ClientModel = client_service.create_client(validated_form)
            messages.success(request, "Registro exitoso")
            return redirect("login")
        except Exception as e:
            SignUpExceptionHandler.handle_exception(request, e)
            return redirect("sign-up")
        

app/back/templates/sign-up.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Joyas Celeste</title>
    <link rel="icon" href="{% static 'images/favicon_v2.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% include "tailwind/cdn-tailwind.html" %}
</head>
<body>
    <section class="flex items-center justify-center w-full sm:h-auto sm:py-2 bg-primary-earth_tone_3_light">
        <div class="flex flex-col w-full sm:w-4/5 md:w-3/5 lg:w-2/5 sm:h-full justify-between 
            sm:justify-center gap-y-12 p-6 sm:p-12 bg-white sm:rounded-lg sm:shadow-lg">
            <div class="flex justify-center w-full">
                <img class="w-32 h-20" src="{% static 'images/cj-logo.png' %}" alt="">
            </div>

            <form method="post" enctype="multipart/form-data" id="sign_up_form">
                {% csrf_token %}
                <div class="flex flex-col gap-y-6">
                    <div class="flex flex-col gap-y-2">
                        <label for="id_first_name" class="w-fit cursor-pointer cinzel-semibold">Nombre</label>
                        {{ form.first_name }}
                    </div>
                    <div class="flex flex-col gap-y-2">
                        <label for="id_last_name" class="w-fit cursor-pointer cinzel-semibold">Apellido</label>
                        {{ form.last_name }}
                    </div>

                    <div class="flex flex-col gap-y-2">
                        <label for="id_username" class="w-fit cursor-pointer cinzel-semibold">Email</label>
                        {{ form.username }}
                    </div>
                    <div class="flex flex-col gap-y-2">
                        <label for="id_password" class="w-fit cursor-pointer cinzel-semibold">Contraseña</label>
                        <div class="relative">
                            {{ form.password }}
                            <button type="button" id="toggle_password" class="absolute right-2 top-2 
                                text-primary-earth_tone_4">
                                <svg id="eye_icon" xmlns="http://www.w3.org/2000/svg" fill="none" 
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                </svg>
                                <svg id="eye_slash_icon" xmlns="http://www.w3.org/2000/svg" fill="none" 
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 hidden">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.242 4.242L9.88 9.88" />
                                </svg>
                            </button>
                        </div>
                    </div>
                    <div class="flex flex-col gap-y-2">
                        <label for="id_repeat_password" class="w-fit cursor-pointer cinzel-semibold">Repetir Contraseña</label>
                        {{ form.repeat_password }}
                    </div>
                </div>
            </form>
            
            {% include "components-base/django-messages.html" with tailwind_class="top-2 md:top-5 left-2 md:left-5 right-2 md:right-5" %}
            
            <div class="flex flex-col sm:flex-row gap-6 w-full">
                <div class="flex justify-center w-full">
                    <button type="submit" id="sign_in_button" class="w-full p-2 bg-primary-earth_tone_4 text-lg
                        text-white rounded-sm mukta-light hover:bg-primary-earth_tone_4_0750">
                        Registrarse
                    </button>
                </div>
                <div class="flex justify-center w-full">
                    <a href="{% url 'login' %}" class="w-full">
                        <button type="button" id="go_to_login" class="w-full p-2 bg-white text-lg 
                            text-primary-earth_tone_4 border border-2 border-primary-earth_tone_4 rounded-sm 
                            mukta-light hover:bg-zinc-50">
                            Ir a inicio de sesión
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </section>
</body>
<script type="module" src="{% static 'js/sign-up.js' %}"></script>
<script src="{% static 'js/tailwind/tailwind.config.js' %}"></script>
</html>